<a href="https://colab.research.google.com/github/Kuldeep9981/Data_science123/blob/main/numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [3]:
#Question1--Write a Numpy program to get the Numpy version.
import numpy as np

np.__version__

'1.25.2'

In [ ]:
#Question2 Write a NumPy program to test whether none of the
# elements of a given array are zero.
arr1=np.array([1,2,4,6,7])
arr2=np.array([14,5,8,0,9])
def array_none_zero(arr):
  return np.all(arr!=0)
print("Any array is conatin not zero then it returns:" ,array_none_zero(arr1))


Any array is conatin not zero then it returns: True


In [ ]:
arr2=np.array([14,5,8,0,9])
print("Any array is contain a zero then it returns:" ,array_none_zero(arr2))

Any array is contain a zero then it returns: False


In [ ]:
#Question3 Write a NumPy program to create an element-wise
# comparison (greater, greater_equal, less and less_equal) of
# two given arrays.
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,4])
arr1[0]>arr2[2]

False

In [ ]:
arr1[3]>=arr2[4]

True

In [ ]:
arr1[2]<arr2[0]

True

In [ ]:
arr1[2]<=arr2[2]

True

In [ ]:
#Question4 Write a NumPy program to create an array with the values
# 1, 7, 13, 105 and determine the size of the memory occupied
# by the array.
arr = np.array([1,7,13,105])
arr.size*arr.itemsize

32

In [ ]:
##Question5 Write a NumPy program to create an array of integers
# from 30 to 70.
arr=np.arange(30,70)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [ ]:
#Question6 Write a NumPy program to create an array of all even
# integers from 30 to 70.

In [ ]:
array  = np.arange(30,70,2)
array

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

In [ ]:
# Write a NumPy program to create a 3x3 identity matrix.
# Write a search NumPy program to create a 3X4 array and
# iterate over it.


In [ ]:
indentity_array = np.eye(3)
indentity_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
array = np.arange(1,13).reshape(3,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
for row in array:
  for element in row:
    print(element,end=" ")


1 2 3 4 5 6 7 8 9 10 11 12 